# fly.toml app configuration file generated for micktwomey-django-test-app on 2025-04-24T20:43:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'micktwomey-django-test-app'
primary_region = 'ams'
console_command = 'uv run python manage.py shell'

[build]

[env]
PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[[statics]]
guest_path = '/code/static'
url_prefix = '/static/'
